first_name = input("Введіть ваше ім'я: ")
last_name = input("Введіть ваше прізвище: ")
age = input("Введіть ваш вік: ")
city = input("Введіть місто проживання: ")
hobbies = input("Введіть ваші хобі: ")
print("\n--- Ваша анкета ---")
print(f"Ім'я: {first_name}")
print(f"Прізвище: {last_name}")
print(f"Вік: {age}")
print(f"Місто проживання: {city}")
print(f"Хобі: {hobbies}")
